#!/usr/bin/env bash
# Check if all required parameters are provided

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
SSH_USERNAME="$3"
SSH_KEY="$4"

# Transfer file using scp
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no \
    "$FILE_PATH" "$SSH_USERNAME@$SERVER_IP":~/

# Checking if scp was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Failed to transfer file"
fi
