#!/usr/bin/env bash
# Check if all required parameters are provided

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
private_key="$4"

# Transfer the file using scp
scp -i "$private_key" -o StrictHostKeyChecking=no \
	"$file_path" "$username@$server_ip:~/"

# Verify the transfer
ssh -i "$private_key" "$username@$server_ip" 'ls ~/'
