#!/usr/bin/env bash
# Install Nginx
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Make sure Nginx is running
sudo service nginx start

# Create a basic HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to serve the custom HTML page
sudo bash -c 'echo "server
{
	listen 80;
	server_name localhost;
	location /
	{
		root /var/www/html;
		index index.html;
	}
}" > /etc/nginx/sites-available/default'

# Restart Nginx without using systemctl
sudo kill -s HUP $(cat /var/run/nginx.pid)
# End of script
