#!/usr/bin/env bash
# install nginx with '-y' flag for automatic yes to prompts
apt-get update
apt-get install -y nginx

# Define the redirection configuration
redirection_config="\\n\tlocation /redirect_me {\\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\t}"

# Use sed to replace the default server block configuration with the redirection configuration
sed -i "/server_name _;/c\server_name _;\n$redirection_config" /etc/nginx/sites-available/default


# Restart nginx without using systemctl
/etc/init.d/nginx restart
