#!/usr/bin/env bash
# script to configure Nginx to have a custom 404 page containing the string "Ceci n'est pas une page" on Ubuntu 16.04 LTS

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create custom 404 page
sudo sh -c 'echo "Ceci n'"'"'est pas une page" > /var/www/html/404.html'

# Configure Nginx to use custom 404 page
sudo sh -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx to apply changes
# sudo systemctl restart nginx
sudo nginx -s reload
