#!/usr/bin/env bash
# script to configure Nginx to have a custom 404 page containing the string "Ceci n'est pas une page" on Ubuntu 16.04 LTS

# Update package index
sudo apt update
# Install Nginx
sudo apt install nginx -y

echo " Ceci n'est pas une page " > /var/www/html/404.html

# Define the redirection for page not found configuration
redirection_config="\# Custom 404 error page\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"

# Use sed to replace the default server block configuration with the redirection configuration
sed -i "/server_name _;/c\server_name _;\n$redirection_config" /etc/nginx/sites-available/default

# Restart Nginx using reload command
# sudo nginx -s reload
/etc/init.d/nginx restart
