#!/usr/bin/env bash
# script to configure Nginx to have a custom 404 page containing the string "Ceci n'est pas une page" on Ubuntu 16.04 LTS

# Update package index
sudo apt update
# Install Nginx
sudo apt install nginx -y

# Ensure nginx is listening on port 80
sed -i 's/^\(.*listen\s*\)80/\180/' /etc/nginx/sites-available/default

# Create index.html with "Hello World!" message
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Define the redirection configuration
redirection_config="\\n\tlocation /redirect_me {\\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\t}\n\n\t# Custom 404 error page\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"

# Use sed to replace the default server block configuration with the redirection configuration
sed -i "/server_name _;/c\add_header X-Served-By \$hostname;\n\tserver_name _;\n$redirection_config" /etc/nginx/sites-available/default

echo " Ceci n'est pas une page " > /var/www/html/404.html

# Restart nginx without using systemctl
/etc/init.d/nginx restart
