#!/usr/bin/env bash
# This script checks if Nginx is configured to listen on port 80. If not, it updates the configuration to listen on port 80 and restarts the Nginx service.
if (grep -q "listen\s*80" /etc/nginx/sites-available/default); then
	sed -i 's/\(listen \)80;/\180;/' /etc/nginx/sites-available/default systemctl restart nginx
fi
