#!/usr/bin/env bash

# Display headers
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Retrieve processes and format the output
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | sed '1d'
