#!/usr/bin/env bash

# Display the header for the process list
printf "%-9s %-5s %-5s %-7s %-7s %-5s %-9s %-5s %-9s %s\n" \
    "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "COMMAND"

# Fetch and display process information using ps command in a user-oriented format
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,comm --forest | awk 'NR <= 50 { printf "%-9s %-5s %-5s %-7s %-7s %-5s %-9s %-5s %-9s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 }'
