#!/usr/bin/env bash
# This script tells a story based on /etc/passwd

while IFS=":" read -r username _ userid groupid _ homedir shell; do
    passcode=$(grep "^$username:" /etc/shadow | cut -d':' -f2)
    if [ -z "$passcode" ]; then
        passcode="x"
    fi
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $username"
done < /etc/passwd
