#!/usr/bin/env bash
# Bash script that displays content of the current directory In a list format

for file in *
do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]
    then
        echo "${file#*-}"
    fi
done

