#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Replace user in nginx.conf
sed -i 's/user\s*www-data;/user nginx;/' /etc/nginx/nginx.conf

# Modify Nginx default configuration to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
