#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user\s*www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
