#!/bin/bash
#
## Replace "server01" and "8.8.8.8" with your actual server hostname or IP address
#server="server01"
ip_address="8.8.8.8"

## Use ssh with the private key and connect to the server
ssh -i ~/.ssh/school ubuntu@$ip_address
