#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/school with the user ubuntu.
ip_address="34.201.68.191"

## Use ssh with the private key and connect to the server
ssh -i ~/.ssh/school ubuntu@$ip_address
