#!/usr/bin/env bash

# Script that Generate a 4096-bit RSA key pair
ssh-keygen -t rsa -b 4096 -f school -C "school_key" -N "betty"

# success message
echo "RSA key pair created:"
echo "Private key saved as: ./school"
echo "Public key saved as: ./school.pub"
