#!/usr/bin/env bash

# Generate a 4096-bit RSA key pair
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -C "school_key" -N "betty"

# Display success message
echo "RSA key pair created:"
echo "Private key saved as: ~/.ssh/school"
echo "Public key saved as: ~/.ssh/school.pub"
